apiVersion: apps/v1
kind: Deployment
metadata:
  name: marketviz-deployment
  labels:
    app: marketviz
spec:
  replicas: 1
  selector:
    matchLabels:
      app: marketviz
  template:
    metadata:
      labels:
        app: marketviz
    spec:
      containers:
      - name: marketviz-app
        image: 968950512948.dkr.ecr.us-east-1.amazonaws.com/marketviz:latest
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: ecr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: marketviz-service
spec:
  selector:
    app: marketviz
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: marketviz-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: stockmarketviz.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: marketviz-service
            port:
              number: 80
