 

name: Deploy to Amazon ECS
on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
 
    - name: Deploy to Server 1
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${ { secrets.EC2_SSH_KEY }}
        REMOTE_HOST: ${ { secrets.HOST_DNS }}
        REMOTE_USER: ${ { secrets.USERNAME }}  
        ARGS: "-rlgoDzvc -i --delete"
        SOURCE: "dist/"        
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        TARGET: ${{ secrets.REMOTE_TARGET }}
